In [17]:
import numpy as np
def ss(A, jj):
    """Subfunction for h_trid."""
    return np.sqrt(np.sum(A[jj + 1:, jj] ** 2))

def h_trid(A):
    """
    H_TRID(A) uses Householder method to form a tridiagonal matrix from A.
    Must have a SQUARE SYMMETRIC matrix as the input.
    """
    M, N = A.shape
    if M != N or (A != A.T).any():  # This just screens matrices that can't work.
        raise ValueError("Matrix must be square symmetric only, see help.")

    lngth = len(A)  # Preallocations.
    v = np.zeros(lngth)
    I = np.eye(lngth)
    Aold = A
    finalP=np.eye(lngth)
    for jj in range(lngth - 2):  # Build each vector j and run the whole procedure.
        v[:jj] = 0
        S = ss(Aold, jj)
        v[jj + 1] = np.sqrt(0.5 * (1 + abs(Aold[jj + 1, jj]) / (S + 2 * np.finfo(float).eps)))
        v[jj + 2:] = Aold[jj + 2:, jj] * np.sign(Aold[jj + 1, jj]) / (2 * v[jj + 1] * S + 2 * np.finfo(float).eps)
        P = I - 2 * np.outer(v, v)
        Anew = P @ Aold @ P
        Aold = Anew
        finalP=finalP@P
    Anew[abs(Anew) < 5e-14] = 0  # Tolerance.

    return Anew,finalP

In [24]:
# Test with a matrix
A = np.array([[0, 2, 3],
 [2, 5, 6],
  [3, 6, 0]])
print(A)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

T,Q = h_trid(A)
print(Q.T@A@Q)
print(Q@T@Q.T)
# Output:
# [[ 5.  4.  3.]
#  [ 0. -3. -2.]
#  [ 0.  0. -1.]]
print(Q@Q.T)
# Output:
# [[ 1.  0.  0.]
#  [ 0.  0. -1.]
#  [ 0.  1.  0.]]
np.finfo(float).eps


[[0 2 3]
 [2 5 6]
 [3 6 0]]
[[ 0.00000000e+00 -3.60555128e+00 -6.66133815e-16]
 [-3.60555128e+00  7.07692308e+00  4.61538462e+00]
 [-6.66133815e-16  4.61538462e+00 -2.07692308e+00]]
[[ 0.00000000e+00  2.00000000e+00  3.00000000e+00]
 [ 2.00000000e+00  5.00000000e+00  6.00000000e+00]
 [ 3.00000000e+00  6.00000000e+00 -2.22044605e-15]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -1.64887082e-16]
 [ 0.00000000e+00 -1.64887082e-16  1.00000000e+00]]


2.220446049250313e-16