In [2]:
import numpy as np
def ss(A, jj):
    """Subfunction for h_trid."""
    return np.sqrt(np.sum(A[jj + 1:, jj] ** 2))

def h_trid(A):
    """
    H_TRID(A) uses Householder method to form a tridiagonal matrix from A.
    Must have a SQUARE SYMMETRIC matrix as the input.
    """
    M, N = A.shape
    if M != N or (A != A.T).any():  # This just screens matrices that can't work.
        raise ValueError("Matrix must be square symmetric only, see help.")

    lngth = len(A)  # Preallocations.
    v = np.zeros(lngth)
    I = np.eye(lngth)
    Aold = A
    finalP=np.eye(lngth)
    for jj in range(lngth - 2):  # Build each vector j and run the whole procedure.
        v[:jj+1] = 0
        S = ss(Aold, jj)
        v[jj + 1] = np.sqrt(0.5 * (1 + abs(Aold[jj + 1, jj]) / (S)))
        v[jj + 2:] = Aold[jj + 2:, jj] * np.sign(Aold[jj + 1, jj]) / (2 * v[jj + 1] * S )
        P = I - 2 * np.outer(v, v)
        Anew = P @ Aold @ P
        Aold = Anew
        finalP=finalP@P
    # Anew[abs(Anew) < 5e-14] = 0  # Tolerance.

    return Anew,finalP

In [4]:
# Test with a matrix
A = np.array([[1.36 ,-0.816  ,0.521  , 1.43, -0.144],
[-0.816 ,-0.659,  0.794, -0.173, -0.406],
[ 0.521 , 0.794, -0.541,  0.461 , 0.179],
[  1.43 ,-0.173 , 0.461,  -1.43 , 0.822],
[-0.144 ,-0.406 , 0.179,  0.822  ,-1.37]])
print(A)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
import numpy as np
from scipy.linalg import hessenberg
T,Q  = hessenberg(A,calc_q=True)
print(T)
print(Q)
print(Q.T@A@Q)
print(Q@T@Q.T)
# Output:
# [[ 5.  4.  3.]
#  [ 0. -3. -2.]
#  [ 0.  0. -1.]]
print(Q@Q.T)
# Output:
# [[ 1.  0.  0.]
#  [ 0.  0. -1.]
#  [ 0.  1.  0.]]
np.finfo(float).eps


[[ 1.36  -0.816  0.521  1.43  -0.144]
 [-0.816 -0.659  0.794 -0.173 -0.406]
 [ 0.521  0.794 -0.541  0.461  0.179]
 [ 1.43  -0.173  0.461 -1.43   0.822]
 [-0.144 -0.406  0.179  0.822 -1.37 ]]


ValueError: too many values to unpack (expected 2)